language: php
php:
  - 7.1
install:
  - composer --no-interaction install
script: phpunit --configuration phpunit.xml --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
